lzc-sdk-version: "0.1"
name: Teemii
package: cloud.lazycat.app.teemii
version: 0.8.2
description: 一款精简的漫画阅读程序
homepage: https://github.com/dokkaner/teemii
author: dokkaner
application:
  subdomain: teemii
  background_task: false
  multi_instance: true
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://teemii-frontend.cloud.lazycat.app.teemii.lzcapp:80/
services:
  teemii-frontend:
    image: registry.lazycat.cloud/czyt/dokkaner/teemii-frontend:e6f0c92c2561a159
    environment:
      - VITE_APP_TITLE=Teemii
      - VITE_APP_PORT=80
    depends_on:
      - teemii-backend

  teemii-backend:
    image: registry.lazycat.cloud/czyt/dokkaner/teemii-backend:fc5026a292255b7c
    environment:
      - EXPRESS_PORT=3000
      - SOCKET_IO_PORT=1555
    ingress:
      - protocol: tcp
        port: 3000
        service: teemii-backend

      - protocol: tcp
        port: 1555
        service: teemii-backend

    binds:
      - /lzcapp/var/data:/data
